# Main azure-pipelines configuration for the OpenXR-SDK repo.

trigger:
  branches:
    include:
      - '*'

parameters:
- name: NuGetPackageVersionRevision
  type: number
  default: 0

stages:
- stage: Build
  jobs:
  - template: build_jobs.yml
